yandex_vpc_network.network_resource_name.id

yandex_vpc_subnet.subnet_resource_name.zone

yandex_vpc_subnet.subnet_resource_name.id

yandex_vpc_security_group.security_group_name.id

yandex_logging_group.log_group_resoruce_name.id

yandex_iam_service_account.service_account_resource_name.id

yandex_iam_service_account.node_service_account_resource_name.id

yandex_kms_symmetric_key.kms_key_resource_name.id
